---
# Task to write the terraform variables for the Infra build.

- name: tf-vars - extract and view the infrastructure name from the Ignition config file metadata
  command: "jq -r .infraID {{ install_dir }}/metadata.json"
  register: infra_name

- name: tf-vars -  Obtain the hosted zone ID for the Route 53 base domain
  shell: "aws route53 list-hosted-zones-by-name --dns-name {{ base_domain }} --query 'HostedZones[0].Id' --output text | sed 's#/hostedzone/##'"
  register: hosted_zone_output

- name: "modules/set-vars - {{ root_name }} - set values"
  set_fact:
    InfrastructureName: "{{ infra_name['stdout'] }}"
    HostedZoneId: "{{ hosted_zone_output['stdout'] }}"

- name: tf-vars - Create terraform.tfvars
  template:
    src: terraform.tfvars.j2
    dest: "../aws-infra-build/terraform.tfvars"
